version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "thewildmage"
    labels:
      - "scope: meta"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "thewildmage"
    labels:
      - "scope: meta"
