---
default: true

"first-line-h1": false # because of ---json front matter
"line-length": false
"list-marker-space":
    ul_single: 3
    ul_multi: 3
"no-hard-tabs": false
"ul-indent":
    indent: 4
